AllCops:
  TargetRubyVersion: 2.4

# Disabling this cop as it only a prep for Ruby 3.0
# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FrozenStringLiteralComment
Style/FrozenStringLiteralComment:
  Enabled: false

# Setting line length to 120 characters
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15